import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar";
import {Box, Text} from "@chakra-ui/react";
import React from "react";
import Header from "../components/Header";

export default function Home() {
  return (
      <Box bg={"gray.50"}>
          <div>
              <Head>
                  <title>Adventurous</title>
                  <meta name="description" content="Generated by create next app"/>
                  <link rel="icon" href="/favicon.ico"/>
              </Head>

              <Header/>



              <Box mt={100} color={"#3e4d3a"}>
                  <h1 className={styles.title}>
                      Welcome to <Text display={"inline"} color={"g.2"}>Adventurous !</Text>
                  </h1></Box>



          </div>
      </Box>
  )
}
