import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar";
import {Box, Text} from "@chakra-ui/react";
import React from "react";
import Header from "../components/Header";
import ActivityCard from "../components/home/ActivityCard";

export default function Home() {
  return (
      <Box bg={"gray.50"}>
          <div>
              <Head>
                  <title>Adventurous</title>
                  <meta name="description" content="Generated by create next app"/>
                  <link rel="icon" href="/favicon.ico"/>
              </Head>

              <Header/>



              <ActivityCard/>



          </div>
      </Box>
  )
}
